//created by jenya


//CI
pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('docker')
	}

	stages {
	    
	    stage('gitclone') {

			steps {
				git 'https://github.com/jenyaTopol/myGithubRepo.git'
			}
		}

		stage('Build') {

			steps {
				sh 'docker build -t myDockerHub/myRepo:latest .'
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push myDockerHub/myRepo'
			}
		}
	}
	//CD
	post {
		always {
			sh 'docker logout'
		}
		
	}

}
